import Head from "next/head";
import Layout from "@/components/Layout";
import { Container, Typography, Grid, TextField } from "@mui/material";
import { createClient } from "contentful";
import { GetStaticProps } from "next";
import RecipeCard from "@/components/RecipeCard";
import SearchIcon from "@mui/icons-material/Search";
import InputAdornment from "@mui/material/InputAdornment";

export const getStaticProps: GetStaticProps = async () => {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID as string,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN ?? "",
  });

  const res = await client.getEntries({ content_type: "recipe" });

  return {
    props: {
      recipes: res.items,
    },
  };
};
export default function Home({ recipes }: any) {
  console.log(recipes);
  return (
    <>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Container>
          <Typography
            variant="h2"
            component="h1"
            sx={{ textAlign: "center", my: 5 }}
          >
            Find your Perfect Recipe!
          </Typography>
          <TextField
            fullWidth
            sx={{ mb: 3 }}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <SearchIcon />
                </InputAdornment>
              ),
            }}
          ></TextField>
          <Grid container>
            <Grid item lg={4}>
              {recipes.map((recipe: any) => (
                <RecipeCard key={recipe.sys.id} recipe={recipe}></RecipeCard>
              ))}
            </Grid>
          </Grid>
        </Container>
      </Layout>
    </>
  );
}
